# Generated by Django 3.0.5 on 2020-04-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name']},
        ),
    ]
